name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # Trigger the workflow on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        run: |
          echo "The primary image URL will be: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main"
          echo "Other tags might be: ${{ steps.meta.outputs.tags }}"
          echo "::set-output name=main_url::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main" # This makes the URL available for later steps if needed
